[package]
name = "rul"
version = "0.1.0"
description = "Rust Utility Library."
repository = "https://gitlab.com/ragagno/rul"

authors = ["Ragagno <ragocraft@gmail.com>"]
license = "MIT"

edition = "2018"

readme = "README.md"
